name: package list

on: workflow_dispatch

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: dpkg-query -W --showformat='${Installed-Size}\t${Package}\n' | awk '{printf "%10.2f MB \t%s\n", $1/1024, $2}' | sort -n > package_list.txt
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release
          files: package_list.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
