name: package list

on: workflow_dispatch

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      -
        name: Code checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU for arm64
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64
      -
        name: ubuntu 24.04/arm64
        env:
          LATEST_VERSION: "version_2.3.1"
          DPKG_ARCH: "amd64"
          APPIMAGE_ARCH: "amd64"
          ARCH: "amd64"
        run: |
          docker run --env DPKG_ARCH --env APPIMAGE_ARCH --env ARCH --platform linux/amd64 -v "$(pwd)":/app --workdir=/app debian:bullseye ./build.sh
