name: package list

on: workflow_dispatch

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      -
        name: Code checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU for amd64
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64
      -
        name: ubuntu 24.04/amd64
        env:
          LATEST_VERSION: "version_2.3.1"
          DPKG_ARCH: "amd64"
          APPIMAGE_ARCH: "amd64"
          ARCH: "amd64"
        run: |
         dpkg-query -W --showformat='${Installed-Size}\t${Package}\n' | awk '{printf "%10.2f MB \t%s\n", $1/1024, $2}' | sort -n && docker run --env DPKG_ARCH --env APPIMAGE_ARCH --env ARCH --platform linux/amd64 -v "$(pwd)":/app --workdir=/app ubuntu:24.04 bash build.sh
      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release
          files: |
           package_list_size_in_bytes.txt 
           package_list_size_in_MB.txt
           total_size.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
