name: package list

on: workflow_dispatch

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: docker run --platform linux/amd64 -v "$(pwd)":/app --workdir=/app ubuntu:minimal cat /etc/*ease
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release
          files: package_list.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
